services:
  app:
    image: book-service
    build:
      context: .
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/book_db
      - DATABASE_USER=yu71
      - DATABASE_PASSWORD=53cret
    depends_on:
      - db
    ports:
      - "8080:8080" # Adjust based on your Vert.x app port
  db:
    image: postgres:17-alpine3.21
    container_name: postgres-db
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: yu71
      POSTGRES_PASSWORD: 53cret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
