services:
  db:
    image: postgres:17-alpine3.21
    container_name: postgres-db
    environment:
      POSTGRES_DB: book_db
      POSTGRES_USER: yu71
      POSTGRES_PASSWORD: 53cret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
